/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesDirector;

import Clases.Conector;
import Frames.PrincipalDirector;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel
 */
public class GestionAlumnos extends javax.swing.JFrame {

    public static int idalumno=0;
    DefaultTableModel model=new  DefaultTableModel();
    
    /**
     * Creates new form GestionAlumnos
     */
    public GestionAlumnos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try {
             PreparedStatement ps=cn.prepareStatement("SELECT * FROM alumno;");
             ResultSet rs=ps.executeQuery();
             
             tabla_gestion_alumnos = new JTable (model);
             jScrollPanel.setViewportView(tabla_gestion_alumnos);
             
             model.addColumn("id");
             model.addColumn("Nombre");
             model.addColumn("Apellido Paterno");
             model.addColumn("Apellido Materno");
             model.addColumn("Semestre");
             model.addColumn("NIA");
             
             while(rs.next()){
                 Object[] fila=new Object[6];
                 for (int i=0; i<6; i++){
                     fila[i]=rs.getObject(i+i);
                 }
                 model.addRow(fila);
                 
             }
             cn.close();
             
            
        } catch (SQLException e){
           System.err.print("Error en el llenado de la tabla");
            
        }
        
        tabla_gestion_alumnos.addMouseListener(new MouseAdapter(){
        
        @Override
        public void mouseClicked(MouseEvent e){
            int fila_point=tabla_gestion_alumnos.rowAtPoint(e.getPoint());
            int columna_point=0;
            
            if(fila_point>=1){
                idalumno=(int)model.getValueAt(fila_point, columna_point);
                Alumnos alumnos=new Alumnos();
                alumnos.setVisible(true);
                dispose();
            }
            
        }
    });//////////////////////////
    }
     public void cerrar1(){
        try {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter()  {
               
                public void windowClosing(WindowEvent e){
                
                    confirmarsalida1();
                
                }
            
            });
            
        } catch (Exception e) {
        }
    }
    
    public void confirmarsalida1(){
        int valor1=JOptionPane.showConfirmDialog(this, "¿Desea cerrar la Aplicacion","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(valor1==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"Hasta Pronto","",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonsalir = new javax.swing.JButton();
        jScrollPanel = new javax.swing.JScrollPane();
        tabla_gestion_alumnos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/flecha-hacia-atras.png"))); // NOI18N
        jButtonsalir.setText("Volver");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 40));

        tabla_gestion_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPanel.setViewportView(tabla_gestion_alumnos);

        jPanel1.add(jScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 620, 270));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setText("Gestion de Alumnos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        PrincipalDirector menuPrincipal = new PrincipalDirector();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JTable tabla_gestion_alumnos;
    // End of variables declaration//GEN-END:variables

    Conector con=new Conector();       //Esto es para que exista conexion con la base de adtos
    Connection cn=con.conexion();
     

}
