/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import FramesDirector.Alumnos;
import FramesDirector.BorrarDatos;
import FramesDirector.GestionAlumnos;
import FramesDirector.GestionCalificaciones;
import FramesDirector.GestionMaterias;
import FramesDirector.InformacionDeAlumnoConCalificacion;
import FramesDirector.Materias;
import FramesDirector.RegistroDocentes;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class PrincipalDirector extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalDirector
     */
    public PrincipalDirector() {
        initComponents();
        cerrar1();
        this.setLocationRelativeTo(null);
    }
    
    public void cerrar1(){
        try {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter()  {
               
                public void windowClosing(WindowEvent e){
                
                    confirmarsalida1();
                
                }
            
            });
            
        } catch (Exception e) {
        }
    }
    
    public void confirmarsalida1(){
        int valor1=JOptionPane.showConfirmDialog(this, "¿Desea cerrar la Aplicacion","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(valor1==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"Hasta Pronto","",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BotonRegistroDeUsuariosDocentes = new javax.swing.JButton();
        BotonGestionDeAlumnos = new javax.swing.JButton();
        BotonBorrarDatosDeTablas = new javax.swing.JButton();
        BotonAlumnos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BotonMaterias = new javax.swing.JButton();
        BotonGestionMaterias = new javax.swing.JButton();
        BotonCalificaciones = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        jLabel1.setText("Control de Calificaciones(Bachillerato General \"Hermanos Serdan\")");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 420, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        jLabel2.setText("BIENVENIDO DIRECTOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 168, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 130, 280));

        jPanel2.setBackground(new java.awt.Color(198, 245, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonRegistroDeUsuariosDocentes.setBackground(new java.awt.Color(255, 102, 102));
        BotonRegistroDeUsuariosDocentes.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonRegistroDeUsuariosDocentes.setText("Registro de Usuarios Docentes");
        BotonRegistroDeUsuariosDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroDeUsuariosDocentesActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegistroDeUsuariosDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        BotonGestionDeAlumnos.setBackground(new java.awt.Color(153, 255, 153));
        BotonGestionDeAlumnos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonGestionDeAlumnos.setText("Gestion de alumnos");
        BotonGestionDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGestionDeAlumnosActionPerformed(evt);
            }
        });
        jPanel2.add(BotonGestionDeAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        BotonBorrarDatosDeTablas.setBackground(new java.awt.Color(153, 255, 153));
        BotonBorrarDatosDeTablas.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonBorrarDatosDeTablas.setText("Borrar datos de tablas");
        BotonBorrarDatosDeTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarDatosDeTablasActionPerformed(evt);
            }
        });
        jPanel2.add(BotonBorrarDatosDeTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 190, -1));

        BotonAlumnos.setBackground(new java.awt.Color(102, 102, 255));
        BotonAlumnos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonAlumnos.setText("Alumnos");
        BotonAlumnos.setToolTipText("");
        BotonAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlumnosActionPerformed(evt);
            }
        });
        jPanel2.add(BotonAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel7.setText("Elige una opción para empezar");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        BotonMaterias.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonMaterias.setText("Materias");
        BotonMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMateriasActionPerformed(evt);
            }
        });
        jPanel2.add(BotonMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        BotonGestionMaterias.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonGestionMaterias.setText("GestionMaterias");
        BotonGestionMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGestionMateriasActionPerformed(evt);
            }
        });
        jPanel2.add(BotonGestionMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, -1));

        BotonCalificaciones.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        BotonCalificaciones.setText("Gestion de Calificaciones");
        BotonCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCalificacionesActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 480, 170));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar-sesion (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistroDeUsuariosDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroDeUsuariosDocentesActionPerformed
        RegistroDocentes registro_docentes = new RegistroDocentes();
        registro_docentes.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegistroDeUsuariosDocentesActionPerformed

    private void BotonGestionDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGestionDeAlumnosActionPerformed
        GestionAlumnos gestion_alumnos = new GestionAlumnos();
        gestion_alumnos.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonGestionDeAlumnosActionPerformed

    private void BotonBorrarDatosDeTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarDatosDeTablasActionPerformed
        BorrarDatos borrar_datos = new BorrarDatos();
        borrar_datos.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonBorrarDatosDeTablasActionPerformed

    private void BotonAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlumnosActionPerformed
        Alumnos alumnos = new Alumnos();
        alumnos.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonAlumnosActionPerformed

    private void BotonMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMateriasActionPerformed
         Materias materias = new Materias();
        materias.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonMateriasActionPerformed

    private void BotonGestionMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGestionMateriasActionPerformed
        GestionMaterias gestion_materias = new GestionMaterias();
        gestion_materias.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonGestionMateriasActionPerformed

    private void BotonCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCalificacionesActionPerformed
        //GestionCalificaciones gestion_calificaciones = new GestionCalificaciones();
        //gestion_calificaciones.setVisible(true);
        //dispose();
        
        InformacionDeAlumnoConCalificacion calificaciones = new InformacionDeAlumnoConCalificacion();
        calificaciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonCalificacionesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrincipalDirector().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlumnos;
    private javax.swing.JButton BotonBorrarDatosDeTablas;
    private javax.swing.JButton BotonCalificaciones;
    private javax.swing.JButton BotonGestionDeAlumnos;
    private javax.swing.JButton BotonGestionMaterias;
    private javax.swing.JButton BotonMaterias;
    private javax.swing.JButton BotonRegistroDeUsuariosDocentes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
